# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys
import os
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        # Main directory (Pyinstaller friendly code)
        if getattr(sys, 'frozen', False):
            self.main_dir = os.path.dirname(sys.executable)
        else:
            self.main_dir = os.path.dirname(os.path.abspath(__file__))
            
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(483, 641)
        MainWindow.setFixedSize(483, 641) # makes it so that you can't resize the window
        
        # Defining each widget and its properties (from QtDesigner)
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox1 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox1.setGeometry(QtCore.QRect(20, 20, 441, 101))
        self.groupBox1.setObjectName("groupBox1")
        self.button1 = QtWidgets.QPushButton(self.groupBox1)
        self.button1.setGeometry(QtCore.QRect(10, 20, 91, 31))
        self.button1.setObjectName("button1")
        self.label1 = QtWidgets.QLabel(self.groupBox1)
        self.label1.setGeometry(QtCore.QRect(110, 24, 321, 27))
        self.label1.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label1.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label1.setObjectName("label1")
        self.button2 = QtWidgets.QPushButton(self.groupBox1)
        self.button2.setGeometry(QtCore.QRect(10, 60, 91, 31))
        self.button2.setObjectName("button2")
        self.label2 = QtWidgets.QLabel(self.groupBox1)
        self.label2.setGeometry(QtCore.QRect(110, 64, 321, 27))
        self.label2.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.label2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.label2.setObjectName("label2")
        
        self.groupBox2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox2.setGeometry(QtCore.QRect(20, 130, 441, 451))
        self.groupBox2.setObjectName("groupBox2")
        
        
        self.table1 = QtWidgets.QTableWidget(self.groupBox2)
        self.table1.setGeometry(QtCore.QRect(10, 60, 221, 381))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table1.sizePolicy().hasHeightForWidth())
        self.table1.setSizePolicy(sizePolicy)
        self.table1.setLineWidth(1)
        self.table1.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.table1.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table1.setDragDropOverwriteMode(False)
        self.table1.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.table1.setObjectName("table1")
        self.table1.setColumnCount(2)
        #self.table1.setRowCount(0)
        
        item = QtWidgets.QTableWidgetItem()
        self.table1.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table1.setHorizontalHeaderItem(1, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.table1.setItem(0, 0, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.table1.setItem(0, 1, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.table1.setItem(1, 0, item)
        # item = QtWidgets.QTableWidgetItem()
        # self.table1.setItem(1, 1, item)
        
        #self.table1.setColumnWidth(1, 40)
        #self.table1.horizontalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        #self.table1.horizontalHeader().setSectionResizeMode(1, QtWidgets.QHeaderView.Stretch)
        self.table1.horizontalHeader().setVisible(True)
        self.table1.horizontalHeader().setCascadingSectionResizes(False)
        self.table1.horizontalHeader().setStretchLastSection(True)
        self.table1.verticalHeader().setVisible(True)
        self.table1.verticalHeader().setCascadingSectionResizes(False)
        self.table1.verticalHeader().setHighlightSections(True)
        self.table1.verticalHeader().setSortIndicatorShown(False)
        self.table1.verticalHeader().setStretchLastSection(False)
        
        
        self.list1 = QtWidgets.QListWidget(self.groupBox2)
        self.list1.setGeometry(QtCore.QRect(250, 60, 181, 341))
        #self.list1.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.list1.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.list1.setObjectName("list1")
        # item = QtWidgets.QListWidgetItem()
        # self.list1.addItem(item)
        # item = QtWidgets.QListWidgetItem()
        # self.list1.addItem(item)
        self.button4 = QtWidgets.QPushButton(self.groupBox2)
        self.button4.setGeometry(QtCore.QRect(250, 410, 181, 31))
        self.button4.setObjectName("button4")
        self.button3 = QtWidgets.QPushButton(self.groupBox2)
        self.button3.setGeometry(QtCore.QRect(10, 20, 91, 31))
        self.button3.setObjectName("button3")
        self.label3 = QtWidgets.QLabel(self.groupBox2)
        self.label3.setGeometry(QtCore.QRect(110, 30, 321, 21))
        self.label3.setObjectName("label3")
        MainWindow.setCentralWidget(self.centralwidget)
        
        ### Tools and Help ###
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 479, 21))
        self.menubar.setObjectName("menubar")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        # Process Moodle zip
        self.actionMoodle = QtWidgets.QAction(MainWindow)
        self.actionMoodle.setObjectName("actionMoodle")
        self.menuTools.addAction(self.actionMoodle)
        self.menubar.addAction(self.menuTools.menuAction())
        
        # Clear results tab
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.menuTools.addAction(self.actionClear)
        self.menubar.addAction(self.menuTools.menuAction())
        
        # Reset all tab
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.menuTools.addAction(self.actionReset)
        self.menubar.addAction(self.menuTools.menuAction())
        
        # Documentation tab
        self.actionDocumentation_PDF = QtWidgets.QAction(MainWindow)
        self.actionDocumentation_PDF.setObjectName("actionDocumentation_PDF")
        self.menuHelp.addAction(self.actionDocumentation_PDF)
        self.menubar.addAction(self.menuHelp.menuAction())
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PyAutoMark"))
        MainWindow.setWindowIcon(QtGui.QIcon(self.main_dir + "\\icon.ico"))
        
        self.groupBox1.setTitle(_translate("MainWindow", "File selection"))
        self.button1.setStatusTip(_translate("MainWindow", "Select the desired assignment key .py file."))
        self.button1.setText(_translate("MainWindow", "Assignment key"))
        self.label1.setText(_translate("MainWindow", ''))
        self.button2.setStatusTip(_translate("MainWindow", "Select the .zip assignment(s) that require marking."))
        self.button2.setText(_translate("MainWindow", "Assignments"))
        self.label2.setText(_translate("MainWindow", ''))
        self.groupBox2.setTitle(_translate("MainWindow", "Program execution and results"))
        self.table1.setSortingEnabled(True)
        # item = self.table1.verticalHeaderItem(0)
        # item.setText(_translate("MainWindow", "1"))
        # item = self.table1.verticalHeaderItem(1)
        # item.setText(_translate("MainWindow", "2"))
        
        item = self.table1.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.table1.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Grade"))
        __sortingEnabled = self.table1.isSortingEnabled()
        self.table1.setSortingEnabled(False)
        
        #item = self.table1.item(0, 0)
        # item.setText(_translate("MainWindow", "Bob"))
        # item = self.table1.item(0, 1)
        # item.setText(_translate("MainWindow", "10"))
        # item = self.table1.item(1, 0)
        # item.setText(_translate("MainWindow", "Dylan"))
        # item = self.table1.item(1, 1)
        # item.setText(_translate("MainWindow", "8"))
        self.table1.setSortingEnabled(__sortingEnabled)
        __sortingEnabled = self.list1.isSortingEnabled()
        self.list1.setSortingEnabled(False)
        # item = self.list1.item(0)
        # item.setText(_translate("MainWindow", "Test1"))
        # item = self.list1.item(1)
        # item.setText(_translate("MainWindow", "Test2"))
        self.list1.setSortingEnabled(__sortingEnabled)
        
        # Status tips
        self.button4.setStatusTip(_translate("MainWindow", "Opens the directory that contains the output .txt files."))
        self.button4.setText(_translate("MainWindow", "Open output .txt file directory"))
        self.button3.setStatusTip(_translate("MainWindow", "Initiates the auto-marking process."))
        self.list1.setStatusTip(_translate("MainWindow", "Double-click to open selected .txt file."))
        self.actionMoodle.setStatusTip(_translate("MainWindow", "Used to extract all zipped assignments from a single Moodle zip download."))
        self.actionClear.setStatusTip(_translate("MainWindow", "Clears table and list data."))
        self.actionReset.setStatusTip(_translate("MainWindow", "Clears table and list data and resets saved directories back to the default."))
        
        self.button3.setText(_translate("MainWindow", "Run program"))
        self.label3.setText(_translate("MainWindow", ""))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.actionMoodle.setText(_translate("MainWindow", "Process Moodle zip"))
        self.actionClear.setText(_translate("MainWindow", "Clear results"))
        self.actionReset.setText(_translate("MainWindow", "Reset all"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionDocumentation_PDF.setText(_translate("MainWindow", "Documentation (PDF)"))
        
        self.button3.setEnabled(False)
        self.button4.setEnabled(False)
        self.label1.setWordWrap(True)
        self.label2.setWordWrap(True)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
